Add use case documentation
markphelps/flipt.io pull request #6
Opened 2020-01-13 19:38 UTC by aaronraff

Closes #1

This is still quite a bit of work to be done on this. I wanted to get @markphelps feedback on the A/B testing section before moving onwards.

Let me know what could be better! That way I can apply that sort of style throughout this doc.

2020-01-14 14:11 UTC, markphelps requested changes
Thanks @aaronraff! I think this is a great start and really appreciate your help!

One thing I was thinking about for this use case documentation is that we could try and keep it high level, and focus on the 'what/why', instead of the 'how'. Much like they do with flagr here: https://checkr.github.io/flagr/#/flagr_use_cases, where they use psuedocode and don't really get into the how to create the flags, etc.

I think the Getting Started and Integration docs already do a pretty good job of walking the user how to set flags/segments/rules up via the UI.

I went ahead and made some suggestions, but don't take them as required changes.

Thank you again for all your help on Flipt and now the docs! ❤️

2020-01-14 14:11 UTC, markphelps commented on content/docs/use_cases.md
> +A/B testing can be accomplished by setting up a percentage rollout in Flipt. First you will need to create a segment. This is detailed in [Getting Started]({{< relref "/docs/getting_started" >}}). Yo
```suggestion
A/B testing can be accomplished by setting up a percentage rollout rule in Flipt. See the [Getting Started]({{< relref "/docs/getting_started" >}}) section for how accomplish this.
```

2020-01-14 14:11 UTC, markphelps commented on content/docs/use_cases.md
> +Next you will want to create a flag with some variants by going to **Flags -> New Flag**. For this example I have created two variants: group-a and group-b.
```suggestion
In this example rule, we have two variants that we are targeting, `group-a` and `group-b`, each with a 50% distribution.
```

2020-01-14 14:11 UTC, markphelps commented on content/docs/use_cases.md
> +After you have both your segment and flag created, head on over to the **Targeting** tab in the flag that you just made. Then select **New Rule**. From here you can match on your newly created segmen
```suggestion
```

2020-01-14 14:11 UTC, markphelps commented on content/docs/use_cases.md
> +Next, choose your percentages like so:
```suggestion
```

2020-01-14 14:11 UTC, markphelps commented on content/docs/use_cases.md
> +Now that your A/B testing flag is all set up you can begin to make requests! Using your favorite Flipt gRPC client library, you can call the `Evaluate` method with the request parameters.
```suggestion
An example request to evaluate this rule within your application would look like this:
```

2020-01-14 14:11 UTC, markphelps commented on content/docs/use_cases.md
> +One of the fields in the reulting struct is `Value`. You can check this to determine what landing page to respond with:
```suggestion
The response will contain which variant we should show for this user, either `group-a` or `group-b`:
```

2020-01-14 15:39 UTC, aaronraff commented
Thanks for the feedback @markphelps! Good call on the 'what/why' rather than 'how'. I'll clean this up a bit and add some more use cases in the next day or so.

2020-01-15 14:21 UTC, markphelps approved these changes
Looks great, thank you @aaronraff !

2020-01-15 14:21 UTC, merged